// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.7.0
// source: unique_number.proto

package pb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ErrorCode int32

const (
	ErrorCode_SUCCESS      ErrorCode = 0
	ErrorCode_CLIENT_ERROR ErrorCode = 499
	ErrorCode_SERVER_ERROR ErrorCode = 500
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:   "SUCCESS",
		499: "CLIENT_ERROR",
		500: "SERVER_ERROR",
	}
	ErrorCode_value = map[string]int32{
		"SUCCESS":      0,
		"CLIENT_ERROR": 499,
		"SERVER_ERROR": 500,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_unique_number_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_unique_number_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_unique_number_proto_rawDescGZIP(), []int{0}
}

type UnRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppName string `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
}

func (x *UnRequest) Reset() {
	*x = UnRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unique_number_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnRequest) ProtoMessage() {}

func (x *UnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_unique_number_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnRequest.ProtoReflect.Descriptor instead.
func (*UnRequest) Descriptor() ([]byte, []int) {
	return file_unique_number_proto_rawDescGZIP(), []int{0}
}

func (x *UnRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

type UnResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode ErrorCode `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=pb.ErrorCode" json:"error_code,omitempty"`
	ErrorMsg  string    `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	Seq       string    `protobuf:"bytes,3,opt,name=seq,proto3" json:"seq,omitempty"`
}

func (x *UnResponse) Reset() {
	*x = UnResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unique_number_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnResponse) ProtoMessage() {}

func (x *UnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_unique_number_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnResponse.ProtoReflect.Descriptor instead.
func (*UnResponse) Descriptor() ([]byte, []int) {
	return file_unique_number_proto_rawDescGZIP(), []int{1}
}

func (x *UnResponse) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_SUCCESS
}

func (x *UnResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *UnResponse) GetSeq() string {
	if x != nil {
		return x.Seq
	}
	return ""
}

var File_unique_number_proto protoreflect.FileDescriptor

var file_unique_number_proto_rawDesc = []byte{
	0x0a, 0x13, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x26, 0x0a, 0x09, 0x55, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x70, 0x70, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x70, 0x70, 0x4e, 0x61, 0x6d,
	0x65, 0x22, 0x69, 0x0a, 0x0a, 0x55, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2c, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65,
	0x71, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x65, 0x71, 0x2a, 0x3e, 0x0a, 0x09,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43,
	0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0c, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54,
	0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0xf3, 0x03, 0x12, 0x11, 0x0a, 0x0c, 0x53, 0x45, 0x52,
	0x56, 0x45, 0x52, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0xf4, 0x03, 0x32, 0x3f, 0x0a, 0x09,
	0x55, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x32, 0x0a, 0x0f, 0x47, 0x65, 0x74,
	0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x0d, 0x2e, 0x70,
	0x62, 0x2e, 0x55, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x70, 0x62,
	0x2e, 0x55, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_unique_number_proto_rawDescOnce sync.Once
	file_unique_number_proto_rawDescData = file_unique_number_proto_rawDesc
)

func file_unique_number_proto_rawDescGZIP() []byte {
	file_unique_number_proto_rawDescOnce.Do(func() {
		file_unique_number_proto_rawDescData = protoimpl.X.CompressGZIP(file_unique_number_proto_rawDescData)
	})
	return file_unique_number_proto_rawDescData
}

var file_unique_number_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_unique_number_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_unique_number_proto_goTypes = []interface{}{
	(ErrorCode)(0),     // 0: pb.ErrorCode
	(*UnRequest)(nil),  // 1: pb.UnRequest
	(*UnResponse)(nil), // 2: pb.UnResponse
}
var file_unique_number_proto_depIdxs = []int32{
	0, // 0: pb.UnResponse.error_code:type_name -> pb.ErrorCode
	1, // 1: pb.UnService.GetUniqueNumber:input_type -> pb.UnRequest
	2, // 2: pb.UnService.GetUniqueNumber:output_type -> pb.UnResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_unique_number_proto_init() }
func file_unique_number_proto_init() {
	if File_unique_number_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_unique_number_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unique_number_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_unique_number_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_unique_number_proto_goTypes,
		DependencyIndexes: file_unique_number_proto_depIdxs,
		EnumInfos:         file_unique_number_proto_enumTypes,
		MessageInfos:      file_unique_number_proto_msgTypes,
	}.Build()
	File_unique_number_proto = out.File
	file_unique_number_proto_rawDesc = nil
	file_unique_number_proto_goTypes = nil
	file_unique_number_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UnServiceClient is the client API for UnService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UnServiceClient interface {
	GetUniqueNumber(ctx context.Context, in *UnRequest, opts ...grpc.CallOption) (*UnResponse, error)
}

type unServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUnServiceClient(cc grpc.ClientConnInterface) UnServiceClient {
	return &unServiceClient{cc}
}

func (c *unServiceClient) GetUniqueNumber(ctx context.Context, in *UnRequest, opts ...grpc.CallOption) (*UnResponse, error) {
	out := new(UnResponse)
	err := c.cc.Invoke(ctx, "/pb.UnService/GetUniqueNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UnServiceServer is the server API for UnService service.
type UnServiceServer interface {
	GetUniqueNumber(context.Context, *UnRequest) (*UnResponse, error)
}

// UnimplementedUnServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUnServiceServer struct {
}

func (*UnimplementedUnServiceServer) GetUniqueNumber(context.Context, *UnRequest) (*UnResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUniqueNumber not implemented")
}

func RegisterUnServiceServer(s *grpc.Server, srv UnServiceServer) {
	s.RegisterService(&_UnService_serviceDesc, srv)
}

func _UnService_GetUniqueNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnServiceServer).GetUniqueNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UnService/GetUniqueNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnServiceServer).GetUniqueNumber(ctx, req.(*UnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UnService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.UnService",
	HandlerType: (*UnServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUniqueNumber",
			Handler:    _UnService_GetUniqueNumber_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "unique_number.proto",
}
